package bean;
// Generated 15/12/2024 13:39:14 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientesLfm generated by hbm2java
 */
@Entity
@Table(name = "clientes_lfm",
        catalog = "db_lucas_alves"
)
public class ClientesLfm implements java.io.Serializable {

    private int idclientesLfm;
    private String nomeLfm;
    private String apelidoLfm;
    private String cpfLfm;
    private Date dataNascimentoLfm;
    private String senhaLfm;
    private String nivelLfm;
    private String ativoLfm;
    private String emailLfm;
    private String celularLfm;
    private String enderecoLfm;
    private String cepLfm;
    private String cidadeLfm;
    private String bairroLfm;
    private String numeroLfm;

    public ClientesLfm() {
    }

    public ClientesLfm(String nomeLfm, String apelidoLfm, String cpfLfm, String senhaLfm, String nivelLfm, String ativoLfm, String emailLfm, String celularLfm, String enderecoLfm, String cepLfm, String cidadeLfm, String bairroLfm, String numeroLfm) {
        this.nomeLfm = nomeLfm;
        this.apelidoLfm = apelidoLfm;
        this.cpfLfm = cpfLfm;
        this.senhaLfm = senhaLfm;
        this.nivelLfm = nivelLfm;
        this.ativoLfm = ativoLfm;
        this.emailLfm = emailLfm;
        this.celularLfm = celularLfm;
        this.enderecoLfm = enderecoLfm;
        this.cepLfm = cepLfm;
        this.cidadeLfm = cidadeLfm;
        this.bairroLfm = bairroLfm;
        this.numeroLfm = numeroLfm;
    }

    public ClientesLfm(String nomeLfm, String apelidoLfm, String cpfLfm, Date dataNascimentoLfm, String senhaLfm, String nivelLfm, String ativoLfm, String emailLfm, String celularLfm, String enderecoLfm, String cepLfm, String cidadeLfm, String bairroLfm, String numeroLfm) {
        this.nomeLfm = nomeLfm;
        this.apelidoLfm = apelidoLfm;
        this.cpfLfm = cpfLfm;
        this.dataNascimentoLfm = dataNascimentoLfm;
        this.senhaLfm = senhaLfm;
        this.nivelLfm = nivelLfm;
        this.ativoLfm = ativoLfm;
        this.emailLfm = emailLfm;
        this.celularLfm = celularLfm;
        this.enderecoLfm = enderecoLfm;
        this.cepLfm = cepLfm;
        this.cidadeLfm = cidadeLfm;
        this.bairroLfm = bairroLfm;
        this.numeroLfm = numeroLfm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idclientes_lfm", unique = true, nullable = false)
    public int getIdclientesLfm() {
        return this.idclientesLfm;
    }

    public void setIdclientesLfm(int idclientesLfm) {
        this.idclientesLfm = idclientesLfm;
    }

    @Column(name = "nome_lfm", nullable = true, length = 80)
    public String getNomeLfm() {
        return this.nomeLfm;
    }

    public void setNomeLfm(String nomeLfm) {
        this.nomeLfm = nomeLfm;
    }

    @Column(name = "apelido_lfm", nullable = true, length = 25)
    public String getApelidoLfm() {
        return this.apelidoLfm;
    }

    public void setApelidoLfm(String apelidoLfm) {
        this.apelidoLfm = apelidoLfm;
    }

    @Column(name = "cpf_lfm", nullable = true, length = 14)
    public String getCpfLfm() {
        return this.cpfLfm;
    }

    public void setCpfLfm(String cpfLfm) {
        this.cpfLfm = cpfLfm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dataNascimento_lfm", length = 10)
    public Date getDataNascimentoLfm() {
        return this.dataNascimentoLfm;
    }

    public void setDataNascimentoLfm(Date dataNascimentoLfm) {
        this.dataNascimentoLfm = dataNascimentoLfm;
    }

    @Column(name = "senha_lfm", nullable = true, length = 20)
    public String getSenhaLfm() {
        return this.senhaLfm;
    }

    public void setSenhaLfm(String senhaLfm) {
        this.senhaLfm = senhaLfm;
    }

    @Column(name = "nivel_lfm", nullable = true, length = 13)
    public String getNivelLfm() {
        return this.nivelLfm;
    }

    public void setNivelLfm(String nivelLfm) {
        this.nivelLfm = nivelLfm;
    }

    @Column(name = "ativo_lfm", nullable = true, length = 3)
    public String getAtivoLfm() {
        return this.ativoLfm;
    }

    public void setAtivoLfm(String ativoLfm) {
        this.ativoLfm = ativoLfm;
    }

    @Column(name = "email_lfm", nullable = true, length = 80)
    public String getEmailLfm() {
        return this.emailLfm;
    }

    public void setEmailLfm(String emailLfm) {
        this.emailLfm = emailLfm;
    }

    @Column(name = "celular_lfm", nullable = true, length = 10)
    public String getCelularLfm() {
        return this.celularLfm;
    }

    public void setCelularLfm(String celularLfm) {
        this.celularLfm = celularLfm;
    }

    @Column(name = "endereco_lfm", nullable = true, length = 50)
    public String getEnderecoLfm() {
        return this.enderecoLfm;
    }

    public void setEnderecoLfm(String enderecoLfm) {
        this.enderecoLfm = enderecoLfm;
    }

    @Column(name = "cep_lfm", nullable = true, length = 9)
    public String getCepLfm() {
        return this.cepLfm;
    }

    public void setCepLfm(String cepLfm) {
        this.cepLfm = cepLfm;
    }

    @Column(name = "cidade_lfm", nullable = true, length = 50)
    public String getCidadeLfm() {
        return this.cidadeLfm;
    }

    public void setCidadeLfm(String cidadeLfm) {
        this.cidadeLfm = cidadeLfm;
    }

    @Column(name = "bairro_lfm", nullable = true, length = 30)
    public String getBairroLfm() {
        return this.bairroLfm;
    }

    public void setBairroLfm(String bairroLfm) {
        this.bairroLfm = bairroLfm;
    }

    @Column(name = "numero_lfm", nullable = true, length = 10)
    public String getNumeroLfm() {
        return this.numeroLfm;
    }

    public void setNumeroLfm(String numeroLfm) {
        this.numeroLfm = numeroLfm;
    }

}
