package bean;
// Generated 15/12/2024 13:39:14 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasProdutosLfm generated by hbm2java
 */
@Entity
@Table(name = "vendas_produtos_lfm",
         catalog = "db_lucas_alves"
)
public class VendasProdutosLfm implements java.io.Serializable {

    private int idvendasProdutosLfm;
    private int pedidoLfm;
    private int produtosLfm;
    private int quantidadeLfm;
    private double valorUnidadeLfm;
    private String statusLfm;
    private Date dataAdicaoLfm;

    public VendasProdutosLfm() {
    }

    public VendasProdutosLfm(int pedidoLfm, int produtosLfm, int quantidadeLfm, double valorUnidadeLfm, String statusLfm) {
        this.pedidoLfm = pedidoLfm;
        this.produtosLfm = produtosLfm;
        this.quantidadeLfm = quantidadeLfm;
        this.valorUnidadeLfm = valorUnidadeLfm;
        this.statusLfm = statusLfm;
    }

    public VendasProdutosLfm(int pedidoLfm, int produtosLfm, int quantidadeLfm, double valorUnidadeLfm, String statusLfm, Date dataAdicaoLfm) {
        this.pedidoLfm = pedidoLfm;
        this.produtosLfm = produtosLfm;
        this.quantidadeLfm = quantidadeLfm;
        this.valorUnidadeLfm = valorUnidadeLfm;
        this.statusLfm = statusLfm;
        this.dataAdicaoLfm = dataAdicaoLfm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idvendas_produtos_lfm", unique = true, nullable = false)
    public int getIdvendasProdutosLfm() {
        return this.idvendasProdutosLfm;
    }

    public void setIdvendasProdutosLfm(int idvendasProdutosLfm) {
        this.idvendasProdutosLfm = idvendasProdutosLfm;
    }

    @Column(name = "pedido_lfm", nullable = false)
    public int getPedidoLfm() {
        return this.pedidoLfm;
    }

    public void setPedidoLfm(int pedidoLfm) {
        this.pedidoLfm = pedidoLfm;
    }

    @Column(name = "produtos_lfm", nullable = false)
    public int getProdutosLfm() {
        return this.produtosLfm;
    }

    public void setProdutosLfm(int produtosLfm) {
        this.produtosLfm = produtosLfm;
    }

    @Column(name = "quantidade_lfm", nullable = false)
    public int getQuantidadeLfm() {
        return this.quantidadeLfm;
    }

    public void setQuantidadeLfm(int quantidadeLfm) {
        this.quantidadeLfm = quantidadeLfm;
    }

    @Column(name = "valor_unidade_lfm", nullable = false, precision = 10)
    public double getValorUnidadeLfm() {
        return this.valorUnidadeLfm;
    }

    public void setValorUnidadeLfm(double valorUnidadeLfm) {
        this.valorUnidadeLfm = valorUnidadeLfm;
    }

    @Column(name = "status_lfm", nullable = false, length = 10)
    public String getStatusLfm() {
        return this.statusLfm;
    }

    public void setStatusLfm(String statusLfm) {
        this.statusLfm = statusLfm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_adicao_lfm", length = 10)
    public Date getDataAdicaoLfm() {
        return this.dataAdicaoLfm;
    }

    public void setDataAdicaoLfm(Date dataAdicaoLfm) {
        this.dataAdicaoLfm = dataAdicaoLfm;
    }

}
