package bean;
// Generated 15/12/2024 13:39:14 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasLfm generated by hbm2java
 */
@Entity
@Table(name = "vendas_lfm",
        catalog = "db_lucas_alves"
)
public class VendasLfm implements java.io.Serializable {

    private int idvendasLfm;
    private int fkclienteLfm;
    private Date dataLfm;
    private String enderecoLfm;
    private double totalLfm;
    private int produtosLfm;
    private int quantidadeLfm;

    public VendasLfm() {
    }

    public VendasLfm(int fkclienteLfm, String enderecoLfm, double totalLfm, int produtosLfm, int quantidadeLfm) {
        this.fkclienteLfm = fkclienteLfm;
        this.enderecoLfm = enderecoLfm;
        this.totalLfm = totalLfm;
        this.produtosLfm = produtosLfm;
        this.quantidadeLfm = quantidadeLfm;
    }

    public VendasLfm(int fkclienteLfm, Date dataLfm, String enderecoLfm, double totalLfm, int produtosLfm, int quantidadeLfm) {
        this.fkclienteLfm = fkclienteLfm;
        this.dataLfm = dataLfm;
        this.enderecoLfm = enderecoLfm;
        this.totalLfm = totalLfm;
        this.produtosLfm = produtosLfm;
        this.quantidadeLfm = quantidadeLfm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idvendas_lfm", unique = true, nullable = false)
    public int getIdvendasLfm() {
        return this.idvendasLfm;
    }

    public void setIdvendasLfm(int idvendasLfm) {
        this.idvendasLfm = idvendasLfm;
    }

    @Column(name = "fkcliente_lfm", nullable = true)
    public int getFkclienteLfm() {
        return this.fkclienteLfm;
    }

    public void setFkclienteLfm(int fkclienteLfm) {
        this.fkclienteLfm = fkclienteLfm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_lfm", nullable = true, length = 10)
    public Date getDataLfm() {
        return this.dataLfm;
    }

    public void setDataLfm(Date dataLfm) {
        this.dataLfm = dataLfm;
    }

    @Column(name = "endereco_lfm", nullable = true, length = 80)
    public String getEnderecoLfm() {
        return this.enderecoLfm;
    }

    public void setEnderecoLfm(String enderecoLfm) {
        this.enderecoLfm = enderecoLfm;
    }

    @Column(name = "total_lfm", nullable = true, precision = 10)
    public double getTotalLfm() {
        return this.totalLfm;
    }

    public void setTotalLfm(double totalLfm) {
        this.totalLfm = totalLfm;
    }

    @Column(name = "produtos_lfm", nullable = true)
    public int getProdutosLfm() {
        return this.produtosLfm;
    }

    public void setProdutosLfm(int produtosLfm) {
        this.produtosLfm = produtosLfm;
    }

    @Column(name = "quantidade_lfm", nullable = true)
    public int getQuantidadeLfm() {
        return this.quantidadeLfm;
    }

    public void setQuantidadeLfm(int quantidadeLfm) {
        this.quantidadeLfm = quantidadeLfm;
    }

}
